tube_x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tube_y: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tube_radius: 0.0762
covar1: [1, 1]
covar2: [1, 1]
tube_var: 0.0
slip_max: 0.2
trans_var: 0.02
rot_var: 0.26
max_range: 5
